[package]
name = "shaclog"
version = "0.1.0"
authors = ["Poppy - <me@poppyio.com>"]
edition = "2021"
description = "A SHACL to Datalog transpiler"
readme = "README.md"
repository = "https://github.com/poppy-io/SHACLog"
license = "AGPL-3.0"

[dependencies]
